platform :ios, '7.0'
inhibit_all_warnings!

pod 'FMDB'
pod 'THLabel'
pod 'TouchXML'
pod 'ZipArchive'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'ASIHTTPRequest/Core'
pod 'XMTopScrollView'
pod 'XMCommon'

pod 'MJRefresh', '3.1.0'